package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/atvirokodosprendimai/wgmesh/eidos/eidosmeta"
)

var matrixDimensions = []string{"api", "behavior", "cli", "wire"}

type FeatureStatus struct {
	Name       string
	Slug       string
	Status     eidosmeta.Status
	Dimensions []DimensionStatus
}

type DimensionStatus struct {
	Name    string
	Present bool
	Note    string
}

func RenderStatus(features []FeatureStatus) string {
	features = append([]FeatureStatus(nil), features...)
	sort.Slice(features, func(i, j int) bool {
		if features[i].Name == features[j].Name {
			return features[i].Slug < features[j].Slug
		}
		return features[i].Name < features[j].Name
	})

	var b strings.Builder
	b.WriteString("<!-- DO NOT EDIT: generated by `make status` -->\n")
	b.WriteString("# Feature Ledger Status\n\n")
	b.WriteString("## Matrix\n\n")
	b.WriteString("| Feature | Status | API | Behavior | CLI | Wire |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- |\n")

	stats := statusStats{features: len(features)}
	var gaps []string
	for _, feature := range features {
		switch feature.Status {
		case eidosmeta.StatusImplemented:
			stats.implemented++
		case eidosmeta.StatusProvisional:
			stats.provisional++
		}

		byDimension := map[string]DimensionStatus{}
		for _, dimension := range feature.Dimensions {
			byDimension[dimension.Name] = dimension
			stats.claimed++
			if dimension.Present {
				stats.satisfied++
			} else {
				stats.missing++
				gaps = append(gaps, fmt.Sprintf("- %s / %s: %s", feature.Name, dimension.Name, dimension.Note))
			}
		}

		b.WriteString("| ")
		b.WriteString(escapeTableCell(feature.Name))
		b.WriteString(" | ")
		b.WriteString(string(feature.Status))
		for _, dimension := range matrixDimensions {
			status := "-"
			if entry, ok := byDimension[dimension]; ok {
				if entry.Present {
					status = "OK"
				} else {
					status = "MISSING"
				}
			}
			b.WriteString(" | ")
			b.WriteString(status)
		}
		b.WriteString(" |\n")
	}

	b.WriteString("\n## Gap Roster\n\n")
	if len(gaps) == 0 {
		b.WriteString("No missing claimed dimensions.\n")
	} else {
		sort.Strings(gaps)
		for _, gap := range gaps {
			b.WriteString(gap)
			b.WriteString("\n")
		}
	}

	b.WriteString("\n## Summary\n\n")
	b.WriteString(fmt.Sprintf("- Features: %d\n", stats.features))
	b.WriteString(fmt.Sprintf("- Implemented features: %d\n", stats.implemented))
	b.WriteString(fmt.Sprintf("- Provisional features: %d\n", stats.provisional))
	b.WriteString(fmt.Sprintf("- Claimed dimensions: %d\n", stats.claimed))
	b.WriteString(fmt.Sprintf("- Satisfied dimensions: %d\n", stats.satisfied))
	b.WriteString(fmt.Sprintf("- Missing dimensions: %d\n", stats.missing))

	return b.String()
}

type statusStats struct {
	features    int
	implemented int
	provisional int
	claimed     int
	satisfied   int
	missing     int
}

func escapeTableCell(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
