package main

import (
	"strings"
	"testing"

	"github.com/atvirokodosprendimai/wgmesh/eidos/eidosmeta"
)

func TestRenderStatusDeterministicAndSorted(t *testing.T) {
	t.Parallel()

	got := RenderStatus([]FeatureStatus{
		{
			Name:   "zeta feature",
			Slug:   "zeta-feature",
			Status: eidosmeta.StatusProvisional,
			Dimensions: []DimensionStatus{
				{Name: "wire", Present: false, Note: "missing fixture"},
			},
		},
		{
			Name:   "alpha feature",
			Slug:   "alpha-feature",
			Status: eidosmeta.StatusImplemented,
			Dimensions: []DimensionStatus{
				{Name: "cli", Present: true, Note: "testdata/script/alpha-feature.txtar"},
				{Name: "api", Present: false, Note: "openapi.yaml not found or does not reference feature"},
			},
		},
	})

	wantFragments := []string{
		"<!-- DO NOT EDIT: generated by `make status` -->",
		"| Feature | Status | API | Behavior | CLI | Wire |",
		"| alpha feature | implemented | MISSING | - | OK | - |",
		"| zeta feature | provisional | - | - | - | MISSING |",
		"### Provisional / Implementable Features",
		"- zeta feature: provisional",
		"### Missing Compat Artifacts",
		"- alpha feature / api: openapi.yaml not found or does not reference feature",
		"- zeta feature / wire: missing fixture",
		"- Features: 2",
		"- Claimed dimensions: 3",
		"- Satisfied dimensions: 1",
		"- Missing dimensions: 2",
	}
	for _, fragment := range wantFragments {
		if !strings.Contains(got, fragment) {
			t.Fatalf("RenderStatus() missing fragment %q in:\n%s", fragment, got)
		}
	}

	alpha := strings.Index(got, "| alpha feature |")
	zeta := strings.Index(got, "| zeta feature |")
	if alpha == -1 || zeta == -1 || alpha > zeta {
		t.Fatalf("features are not sorted alphabetically:\n%s", got)
	}
	if strings.Contains(strings.ToLower(got), "generated at") || strings.Contains(got, "2026-") {
		t.Fatalf("RenderStatus() should not embed timestamps:\n%s", got)
	}
}

func TestRenderStatusNoGaps(t *testing.T) {
	t.Parallel()

	got := RenderStatus([]FeatureStatus{
		{
			Name:   "alpha",
			Slug:   "alpha",
			Status: eidosmeta.StatusImplemented,
			Dimensions: []DimensionStatus{
				{Name: "cli", Present: true, Note: "testdata/script/alpha.txtar"},
			},
		},
	})

	if !strings.Contains(got, "No provisional or implementable features.") {
		t.Fatalf("RenderStatus() should render empty provisional bucket, got:\n%s", got)
	}
	if !strings.Contains(got, "No missing claimed dimensions.") {
		t.Fatalf("RenderStatus() should render empty missing-artifacts bucket, got:\n%s", got)
	}
	if !strings.Contains(got, "- Missing dimensions: 0") {
		t.Fatalf("RenderStatus() should render missing dimension summary, got:\n%s", got)
	}
}

func TestRenderStatusGapRosterBuckets(t *testing.T) {
	t.Parallel()

	got := RenderStatus([]FeatureStatus{
		{
			Name:       "provisional empty",
			Slug:       "provisional-empty",
			Status:     eidosmeta.StatusProvisional,
			Dimensions: nil,
		},
		{
			Name:   "implemented missing",
			Slug:   "implemented-missing",
			Status: eidosmeta.StatusImplemented,
			Dimensions: []DimensionStatus{
				{Name: "cli", Present: false, Note: "missing testdata/script/implemented-missing*.txtar"},
			},
		},
		{
			Name:       "implemented clean",
			Slug:       "implemented-clean",
			Status:     eidosmeta.StatusImplemented,
			Dimensions: nil,
		},
	})

	provisionalHeading := strings.Index(got, "### Provisional / Implementable Features")
	missingHeading := strings.Index(got, "### Missing Compat Artifacts")
	if provisionalHeading == -1 || missingHeading == -1 || provisionalHeading > missingHeading {
		t.Fatalf("RenderStatus() did not render gap roster buckets in order:\n%s", got)
	}

	provisionalEntry := "- provisional empty: provisional"
	missingEntry := "- implemented missing / cli: missing testdata/script/implemented-missing*.txtar"
	if !strings.Contains(got, provisionalEntry) {
		t.Fatalf("RenderStatus() missing provisional entry %q in:\n%s", provisionalEntry, got)
	}
	if !strings.Contains(got, missingEntry) {
		t.Fatalf("RenderStatus() missing missing-artifacts entry %q in:\n%s", missingEntry, got)
	}
	if strings.Contains(got, "implemented clean /") || strings.Contains(got, "- implemented clean:") {
		t.Fatalf("RenderStatus() should not include clean implemented feature in gap roster:\n%s", got)
	}
	if strings.Index(got, provisionalEntry) > missingHeading {
		t.Fatalf("provisional entry rendered outside provisional bucket:\n%s", got)
	}
	if strings.Index(got, missingEntry) < missingHeading {
		t.Fatalf("missing-artifacts entry rendered outside missing-artifacts bucket:\n%s", got)
	}
}
