name: Feature Request
description: Suggest a new feature or enhancement for wgmesh
title: "[Feature] "
labels: ["type: feature", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. This request will be automatically triaged by Copilot.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like wgmesh to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.
      placeholder: I've also considered...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of wgmesh does this relate to?
      options:
        - Centralized mode (SSH deploy)
        - Decentralized mode (daemon/discovery)
        - Crypto / Security
        - CLI / UX
        - Docker / Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (your assessment)
      description: How important is this to your use case?
      options:
        - Nice to have
        - Important
        - Critical / Blocking
    validations:
      required: true
