// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/rpc/proto/wgmesh.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerInfo represents a single WireGuard mesh peer.
type PeerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pubkey           string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Hostname         string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MeshIp           string                 `protobuf:"bytes,3,opt,name=mesh_ip,proto3" json:"mesh_ip,omitempty"`
	Endpoint         string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	LastSeen         string                 `protobuf:"bytes,5,opt,name=last_seen,proto3" json:"last_seen,omitempty"`
	DiscoveredVia    []string               `protobuf:"bytes,6,rep,name=discovered_via,proto3" json:"discovered_via,omitempty"`
	RoutableNetworks []string               `protobuf:"bytes,7,rep,name=routable_networks,proto3" json:"routable_networks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_wgmesh_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *PeerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PeerInfo) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *PeerInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerInfo) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *PeerInfo) GetDiscoveredVia() []string {
	if x != nil {
		return x.DiscoveredVia
	}
	return nil
}

func (x *PeerInfo) GetRoutableNetworks() []string {
	if x != nil {
		return x.RoutableNetworks
	}
	return nil
}

// PeersListResult is returned by the peers.list RPC method.
type PeersListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersListResult) Reset() {
	*x = PeersListResult{}
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersListResult) ProtoMessage() {}

func (x *PeersListResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersListResult.ProtoReflect.Descriptor instead.
func (*PeersListResult) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_wgmesh_proto_rawDescGZIP(), []int{1}
}

func (x *PeersListResult) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// PeersCountResult is returned by the peers.count RPC method.
type PeersCountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        int64                  `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Dead          int64                  `protobuf:"varint,3,opt,name=dead,proto3" json:"dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersCountResult) Reset() {
	*x = PeersCountResult{}
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersCountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersCountResult) ProtoMessage() {}

func (x *PeersCountResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersCountResult.ProtoReflect.Descriptor instead.
func (*PeersCountResult) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_wgmesh_proto_rawDescGZIP(), []int{2}
}

func (x *PeersCountResult) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *PeersCountResult) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PeersCountResult) GetDead() int64 {
	if x != nil {
		return x.Dead
	}
	return 0
}

// DaemonStatusResult is returned by the daemon.status RPC method.
type DaemonStatusResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeshIp        string                 `protobuf:"bytes,1,opt,name=mesh_ip,proto3" json:"mesh_ip,omitempty"`
	Pubkey        string                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Uptime        int64                  `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Interface     string                 `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonStatusResult) Reset() {
	*x = DaemonStatusResult{}
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatusResult) ProtoMessage() {}

func (x *DaemonStatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatusResult.ProtoReflect.Descriptor instead.
func (*DaemonStatusResult) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_wgmesh_proto_rawDescGZIP(), []int{3}
}

func (x *DaemonStatusResult) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *DaemonStatusResult) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *DaemonStatusResult) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *DaemonStatusResult) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *DaemonStatusResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// DaemonPingResult is returned by the daemon.ping RPC method.
type DaemonPingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          bool                   `protobuf:"varint,1,opt,name=pong,proto3" json:"pong,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonPingResult) Reset() {
	*x = DaemonPingResult{}
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonPingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonPingResult) ProtoMessage() {}

func (x *DaemonPingResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonPingResult.ProtoReflect.Descriptor instead.
func (*DaemonPingResult) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_wgmesh_proto_rawDescGZIP(), []int{4}
}

func (x *DaemonPingResult) GetPong() bool {
	if x != nil {
		return x.Pong
	}
	return false
}

func (x *DaemonPingResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// StatusData is used internally for daemon status callbacks.
type StatusData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeshIp        string                 `protobuf:"bytes,1,opt,name=mesh_ip,proto3" json:"mesh_ip,omitempty"`
	Pubkey        string                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Uptime        int64                  `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Interface     string                 `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusData) Reset() {
	*x = StatusData{}
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusData) ProtoMessage() {}

func (x *StatusData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_wgmesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusData.ProtoReflect.Descriptor instead.
func (*StatusData) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_wgmesh_proto_rawDescGZIP(), []int{5}
}

func (x *StatusData) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *StatusData) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *StatusData) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *StatusData) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

var File_pkg_rpc_proto_wgmesh_proto protoreflect.FileDescriptor

const file_pkg_rpc_proto_wgmesh_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/rpc/proto/wgmesh.proto\x12\n" +
	"wgmesh.rpc\"\xe8\x01\n" +
	"\bPeerInfo\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\amesh_ip\x18\x03 \x01(\tR\amesh_ip\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1c\n" +
	"\tlast_seen\x18\x05 \x01(\tR\tlast_seen\x12&\n" +
	"\x0ediscovered_via\x18\x06 \x03(\tR\x0ediscovered_via\x12,\n" +
	"\x11routable_networks\x18\a \x03(\tR\x11routable_networks\"=\n" +
	"\x0fPeersListResult\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.wgmesh.rpc.PeerInfoR\x05peers\"T\n" +
	"\x10PeersCountResult\x12\x16\n" +
	"\x06active\x18\x01 \x01(\x03R\x06active\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04dead\x18\x03 \x01(\x03R\x04dead\"\x96\x01\n" +
	"\x12DaemonStatusResult\x12\x18\n" +
	"\amesh_ip\x18\x01 \x01(\tR\amesh_ip\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\tR\x06pubkey\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x03R\x06uptime\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterface\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"@\n" +
	"\x10DaemonPingResult\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\bR\x04pong\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"t\n" +
	"\n" +
	"StatusData\x12\x18\n" +
	"\amesh_ip\x18\x01 \x01(\tR\amesh_ip\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\tR\x06pubkey\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x03R\x06uptime\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterfaceB<Z:github.com/atvirokodosprendimai/wgmesh/pkg/rpc/proto;rpcpbb\x06proto3"

var (
	file_pkg_rpc_proto_wgmesh_proto_rawDescOnce sync.Once
	file_pkg_rpc_proto_wgmesh_proto_rawDescData []byte
)

func file_pkg_rpc_proto_wgmesh_proto_rawDescGZIP() []byte {
	file_pkg_rpc_proto_wgmesh_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_proto_wgmesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_proto_wgmesh_proto_rawDesc), len(file_pkg_rpc_proto_wgmesh_proto_rawDesc)))
	})
	return file_pkg_rpc_proto_wgmesh_proto_rawDescData
}

var file_pkg_rpc_proto_wgmesh_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_rpc_proto_wgmesh_proto_goTypes = []any{
	(*PeerInfo)(nil),           // 0: wgmesh.rpc.PeerInfo
	(*PeersListResult)(nil),    // 1: wgmesh.rpc.PeersListResult
	(*PeersCountResult)(nil),   // 2: wgmesh.rpc.PeersCountResult
	(*DaemonStatusResult)(nil), // 3: wgmesh.rpc.DaemonStatusResult
	(*DaemonPingResult)(nil),   // 4: wgmesh.rpc.DaemonPingResult
	(*StatusData)(nil),         // 5: wgmesh.rpc.StatusData
}
var file_pkg_rpc_proto_wgmesh_proto_depIdxs = []int32{
	0, // 0: wgmesh.rpc.PeersListResult.peers:type_name -> wgmesh.rpc.PeerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_rpc_proto_wgmesh_proto_init() }
func file_pkg_rpc_proto_wgmesh_proto_init() {
	if File_pkg_rpc_proto_wgmesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_proto_wgmesh_proto_rawDesc), len(file_pkg_rpc_proto_wgmesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_rpc_proto_wgmesh_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_proto_wgmesh_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_proto_wgmesh_proto_msgTypes,
	}.Build()
	File_pkg_rpc_proto_wgmesh_proto = out.File
	file_pkg_rpc_proto_wgmesh_proto_goTypes = nil
	file_pkg_rpc_proto_wgmesh_proto_depIdxs = nil
}
